### ISSUE TITLE
Syncfusion issue

### ISSUE THREAD

**Issue by OmneityTech** [syncfusion/ej2-react-schedule#2]
1. Create a reactjs Project 
2. npm install @syncfusion/ej2-react-schedule
3. npm install @syncfusion/ej2-base
4. Copy the content of index.html, index.js and index.css into the project
5. Create a file sample-base.js and pasted the content from the rec-editor-generate-rule project.

Please help. .
![error-syn](https://user-images.githubusercontent.com/42090577/43706711-c45d1792-9983-11e8-8a44-1244430b4094.png)

**Comment by UmaMaheswariChandrabose** [comment]
The reported problem might have occurred when trying to access the recurrence editor's inner HTML elements before it gets appended to DOM. Within the ComponentDidMount() method of React, the **setRecurreceRule** method of recurrence editor is called, which in turn is trying to access its inner elements before the recurrence editor gets rendered on the page. Therefore, to overcome this problem, we recommend you to use the setTimeout within the ComponentDidMount method as shown below. 

` 
    renderComplete() { 
        let outputElement = document.querySelector('#rule-output'); 
        var obj = this.recObject; 
        setTimeout(function(){ 
               obj.setRecurrenceRule('FREQ=DAILY;INTERVAL=1;COUNT=10'); 
               outputElement.innerText = obj.value; 
        }, 50);  
    } 
`
