### ISSUE TITLE
Other Calendar Types

### ISSUE THREAD

**Issue by pkhodaveissi** [syncfusion/ej2-react-schedule#3]
Hello

Do you have a live demo of this component implementing other calendar types such as Jalali?
or some kind of snippet which shows how that could be implemented?

thanks

**Comment by UmaMaheswariChandrabose** [comment]
Hello Pierre Veissi,

Currently there is no support provided for Jalali calendar type in our React Scheduler, but we have planned to provide the Hijri calendar type support (which is the advanced streamlined version of Jalali calendar) in our upcoming Volume 4, 2018 main release that is expected to be rolled out by the mid of December 2018.

Regards,
C. Uma Maheswari

**Comment by pkhodaveissi** [comment]
thanks
